[processes.swarmui]
command = "/docker-swarmui/start.sh"
shell = "/bin/bash"
directory = "/SwarmUI"

[processes.aria2]
command = "/docker-swarmui/start-aria2c.sh"
shell = "/bin/bash"
directory = "/SwarmUI"
